version: "3"

services:
  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "50051:50051"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vue-frontend
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
